### POST request to dadata api for get suggests address
POST https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/address HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Token {{ DADATA_API_KEY }}

{
    "query": "москва хабар"
}

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 200, "Response status is not 200");
    });
 %}
###
