name: "Github CI/CD works"
on:
  push:
    branches: [ master, stage, dev ]
  pull_request:
    branches: [ master, stage, dev ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: "Starting init"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm install
      - name: building
        run: npm run build
      - name: prettier style check
        run: npm run prettier
      - name: lint check
        run: npm run lint
      - name: running tests
        run: npm test
